name: build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Install JavaCC
      run: |
        cd ~
        mkdir javacc
        cd javacc
        curl -L https://github.com/javacc/javacc/archive/7.0.4.zip --output 7.0.4.zip
        curl -L https://repo1.maven.org/maven2/net/java/dev/javacc/javacc/7.0.4/javacc-7.0.4.jar --output javacc-7.0.4.jar
        curl -L https://github.com/javacc/javacc/archive/javacc-7.0.9.zip --output javacc-7.0.9.zip
        unzip 7.0.4.zip
        cd javacc-7.0.4
        mkdir target
        cp ../javacc-7.0.4.jar target/javacc.jar
        cd ..
        unzip javacc-7.0.9.zip
        cp -r javacc-javacc-7.0.9/scripts javacc-7.0.4
        echo "~/javacc/javacc-7.0.4/scripts" >> $GITHUB_PATH
    
    - name: Build
      run: gradle build
